name: Update Dependencies

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  update:
    name: Update Packages
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          pnpm: true

      - name: Install npm-check-updates
        run: pnpm add -g npm-check-updates

      - name: Upgrade Dependencies
        run: |
          ncu -u
          pnpm install
          pnpm: true

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: auto-update dependencies"
          git push
