name: Update Dependencies

on:
  schedule:
    # Every Monday at 3 am
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:

  checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  update:
    name: Update Packages
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: npm install -g npm-check-updates

      - name: Upgrade dependencies
        run: |
          ncu -u
          npm install

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: auto-update NPM dependencies"
          git push
